### ISSUE TITLE
'ConnectionError' object has no attribute 'message'

### ISSUE THREAD

**Issue by garrymalone** [PureStorage-OpenConnect/rest-client#9]
Receive the error "'ConnectionError' object has no attribute 'message'" when a Pure System request times out.  It appears to be occurring at line 147 in purestorage.py   ---  raise PureError(err.message)

This is in version 1.11.3. 

Please let me know if I can assist or answer any questions. 

Thanks,
Garry

**Comment by garrymalone** [comment]
Found a solution to this issue in my situation.  The storage array IP address had to be added to the AD group that I am in.

**Comment by claudiogianturco** [comment]
> Found a solution to this issue in my situation. The storage array IP address had to be added to the AD group that I am in.

what did u do exactly to solve? can you show the code u used to solve it please? thanks

**Comment by garrymalone** [comment]
It was a change that the Active Directory administrator made.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
